# loading csv testing data in new data model
# find csv file for given table
# load current state table, historic, and source map <-- separate functions
# optional parameters for functions for flags that bypass need for calling separate function
# pandas operator, psycopg 3
# parameterize file input down line
# hash lib <-- use hashlib for hash

from __future__ import annotations

import hashlib
from datetime import datetime, timezone
from pathlib import Path

import click
import pandas
import psycopg
from psycopg import sql

LOAD_USER = "dev_load"

# CSV metadata values are optional unless --metadata-provided is used.
METADATA_COLS = (
    "modified_by_user_id",
    "published_by_user_id",
    "record_effective_dttm",
)

# Hashes are always generated by this script, never provided by the CSV.
HASH_COLS = (
    "lookup_hk",
    "historic_record_hk",
    "record_values_hash",
    "mapping_record_hk",
    "standard_lookup_hk",
)

# These CSV columns are for source_reference_map, not the current lkp table.
MAP_COLS = (
    "record_source_nm",
    "source_reference_cd",
    "source_reference_nm",
)


def hash_value(*values: object) -> str:
    """Return the team's SHA-256 hash for one or more values.

    Each value is trimmed, changed to uppercase, and replaced with
    '__NULL__' when missing or blank. The cleaned values are joined using
    '|', then SHA-256 produces the 64-character hash.
    """
    cleaned = []
    for value in values:
        text = "" if value is None or pandas.isna(value) else str(value).strip()
        cleaned.append(text.upper() if text else "__NULL__")
    return hashlib.sha256("|".join(cleaned).encode("utf-8")).hexdigest()


def table_identifier(table_name: str) -> sql.Identifier:
    """Safely turn a schema-qualified table name into a SQL identifier."""
    parts = table_name.split(".")
    if not table_name or any(not part for part in parts):
        raise ValueError(f"invalid table name: {table_name!r}")
    return sql.Identifier(*parts)


def column_identifier(column_name: str) -> sql.Identifier:
    """Safely turn a column name into a SQL identifier."""
    if not column_name or "." in column_name:
        raise ValueError(f"invalid column name: {column_name!r}")
    return sql.Identifier(column_name)


def read_csv(csv: str) -> pandas.DataFrame:
    """Read the CSV with pandas; strip text and turn blanks into None."""
    path = Path(csv)
    if not path.is_file():
        raise ValueError(f"csv file not found: {csv}")

    df = pandas.read_csv(path, dtype=str, keep_default_na=False)
    df = df.map(lambda value: value.strip() if isinstance(value, str) else value)
    return df.map(lambda value: None if value == "" else value)


def effective_timestamp(value: object) -> str:
    """Return a fixed UTC timestamp string for Postgres and historic hashes."""
    timestamp = pandas.to_datetime(value, utc=True)
    if pandas.isna(timestamp):
        raise ValueError("record_effective_dttm cannot be blank")
    return timestamp.strftime("%Y-%m-%d %H:%M:%S.%f+00")


def prepare_current_rows(
    csv: str,
    primary_code_col: str,
    metadata_provided: bool,
    modified_by_user_id: str,
    published_by_user_id: str,
    record_effective_dttm: object,
) -> tuple[pandas.DataFrame, list[str]]:
    """Read a CSV and add the lkp hash plus metadata columns."""
    df = read_csv(csv)
    required = ("code_set_nm", primary_code_col)
    missing = [column for column in required if column not in df.columns]
    if missing:
        raise ValueError(f"csv is missing required column(s): {missing}")

    included_hashes = [column for column in df.columns if column in HASH_COLS]
    if included_hashes:
        raise ValueError(
            f"csv must not contain hash key column(s): {included_hashes}"
        )

    if metadata_provided:
        missing_metadata = [column for column in METADATA_COLS if column not in df]
        if missing_metadata:
            raise ValueError(
                "metadata_provided=True but csv is missing "
                f"column(s): {missing_metadata}"
            )
        df["record_effective_dttm"] = df["record_effective_dttm"].map(
            effective_timestamp
        )
    else:
        df["modified_by_user_id"] = modified_by_user_id
        df["published_by_user_id"] = published_by_user_id
        df["record_effective_dttm"] = effective_timestamp(record_effective_dttm)

    # Adding hash key column
    # lookup_hk = hash(code_set_nm + primary code)
    df.insert(
        0,
        "lookup_hk",
        [
            hash_value(row["code_set_nm"], row[primary_code_col])
            for row in df.to_dict("records")
        ],
    )

    # A description is not required in the CSV. When absent, it is loaded as
    # NULL and is still included in the historic record-value hash.
    prefix = primary_code_col.removesuffix("_cd")
    desc_col = f"{prefix}_desc"
    if desc_col not in df:
        df[desc_col] = None

    # source-map fields belong in source_reference_map, not lkp_<area>.
    lkp_columns = [
        column for column in df.columns
        if column not in MAP_COLS
    ]
    return df, lkp_columns


def copy_rows(
    conn: psycopg.Connection,
    table_name: str,
    frame: pandas.DataFrame,
    columns: list[str],
    truncate: bool = True,
) -> int:
    """Bulk-copy a DataFrame into a table, optionally truncating first."""
    target = table_identifier(table_name)
    identifiers = [column_identifier(column) for column in columns]
    statement = sql.SQL("COPY {} ({}) FROM STDIN").format(
        target,
        sql.SQL(", ").join(identifiers),
    )

    with conn.cursor() as cur:
        if truncate:
            cur.execute(sql.SQL("TRUNCATE TABLE {}").format(target))
        with cur.copy(statement) as copy:
            for row in frame[columns].itertuples(index=False, name=None):
                copy.write_row(row)
    return len(frame)


def load_current_lkp_table(
    csv,
    trgt_table,
    primary_code_col,
    hist_table=None,
    metadata_provided=False,
    modified_by_user_id=LOAD_USER,
    published_by_user_id=None,
    record_effective_dttm=None,
    conn=None,
):
    """
    Load a current state lookup table from a provided CSV.

    The CSV must include code_set_nm and the primary code column. It is a
    truncate-and-reload process: existing rows in trgt_table are removed and
    the prepared CSV rows are bulk copied in. If hist_table is provided, its
    opening historic rows are loaded from the same prepared data.

    Args:
        csv: Full path to the CSV file to be loaded.
        trgt_table: Target current-state table, including schema name.
        primary_code_col: Column containing the primary code / business key.
        hist_table: Associated historic table. Optional.
        metadata_provided: Use the three metadata columns from the CSV.
        modified_by_user_id: Default modified-by value.
        published_by_user_id: Default published-by value.
        record_effective_dttm: Default effective timestamp.
        conn: Open psycopg connection; caller owns commit/rollback.
    """
    # Validate input
    table_identifier(trgt_table)
    column_identifier(primary_code_col)
    if conn is None:
        raise ValueError("an open psycopg connection is required (conn=...)")
    if published_by_user_id is None:
        published_by_user_id = modified_by_user_id
    if record_effective_dttm is None:
        record_effective_dttm = datetime.now(timezone.utc)

    # Read CSV File / Adding hash key column / Setting metadata columns
    frame, lkp_columns = prepare_current_rows(
        csv,
        primary_code_col,
        metadata_provided,
        modified_by_user_id,
        published_by_user_id,
        record_effective_dttm,
    )

    # Loading table <-- bulk truncate and COPY load
    inserted = copy_rows(conn, trgt_table, frame, lkp_columns, truncate=True)
    print(f"{trgt_table}: replaced with {inserted} row(s)")

    if hist_table:
        load_historic_lkp_table(
            csv,
            hist_table,
            trgt_table,
            primary_code_col,
            current_data=frame,
            conn=conn,
        )
    return inserted


def load_historic_lkp_table(
    csv,
    hist_table,
    current_table,
    primary_code_col,
    current_data=None,
    conn=None,
):
    """
    Load the opening historic lookup rows using the current lookup data.

    historic_record_hk is hash(lookup_hk + record_effective_dttm), while
    record_values_hash is hash(name + description). Like current tables, this
    is a truncate-and-reload process. current_data is passed internally from
    load_current_lkp_table so both tables use the exact same metadata.
    """
    # Validate input
    table_identifier(hist_table)
    table_identifier(current_table)
    column_identifier(primary_code_col)
    if conn is None:
        raise ValueError("an open psycopg connection is required (conn=...)")

    # Read CSV File only when this function is called independently.
    if current_data is None:
        current_data, _ = prepare_current_rows(
            csv,
            primary_code_col,
            metadata_provided=False,
            modified_by_user_id=LOAD_USER,
            published_by_user_id=LOAD_USER,
            record_effective_dttm=datetime.now(timezone.utc),
        )

    prefix = primary_code_col.removesuffix("_cd")
    name_col = f"{prefix}_nm"
    desc_col = f"{prefix}_desc"
    if name_col not in current_data:
        raise ValueError(f"csv is missing required historic name column: {name_col}")

    historic = pandas.DataFrame()
    historic["lookup_hk"] = current_data["lookup_hk"]
    historic["record_values_hash"] = [
        hash_value(row[name_col], row[desc_col])
        for row in current_data.to_dict("records")
    ]
    historic["modified_by_user_id"] = current_data["modified_by_user_id"]
    historic["published_by_user_id"] = current_data["published_by_user_id"]
    historic["record_effective_dttm"] = current_data["record_effective_dttm"]
    historic.insert(
        0,
        "historic_record_hk",
        [
            hash_value(row["lookup_hk"], row["record_effective_dttm"])
            for row in historic.to_dict("records")
        ],
    )
    historic["record_end_dttm"] = None
    historic["deleted_flg"] = False
    historic["active_flg"] = True
    historic["code_set_nm"] = current_data["code_set_nm"]
    historic[primary_code_col] = current_data[primary_code_col]
    historic[name_col] = current_data[name_col]
    historic[desc_col] = current_data[desc_col]

    columns = [
        "historic_record_hk",
        "lookup_hk",
        "record_values_hash",
        *METADATA_COLS,
        "record_end_dttm",
        "deleted_flg",
        "active_flg",
        "code_set_nm",
        primary_code_col,
        name_col,
        desc_col,
    ]
    inserted = copy_rows(conn, hist_table, historic, columns, truncate=True)
    print(f"{hist_table}: replaced with {inserted} row(s)")
    return inserted


def load_reference_map(
    csv,
    primary_code_col,
    map_table="reference.source_reference_map",
    metadata_provided=False,
    modified_by_user_id=LOAD_USER,
    published_by_user_id=None,
    record_effective_dttm=None,
    conn=None,
):
    """
    Load source system mappings from a CSV into source_reference_map.

    The CSV needs record_source_nm and source_reference_cd; source_reference_nm
    is optional. Hashes are generated in Python. The map table is shared by
    the lookup areas, so this function replaces mappings only for the code
    sets in this CSV instead of truncating mappings from every area.
    """
    # Validate input
    table_identifier(map_table)
    column_identifier(primary_code_col)
    if conn is None:
        raise ValueError("an open psycopg connection is required (conn=...)")
    if published_by_user_id is None:
        published_by_user_id = modified_by_user_id
    if record_effective_dttm is None:
        record_effective_dttm = datetime.now(timezone.utc)

    # Read CSV File / Adding hash key column / Setting metadata columns
    frame, _ = prepare_current_rows(
        csv,
        primary_code_col,
        metadata_provided,
        modified_by_user_id,
        published_by_user_id,
        record_effective_dttm,
    )
    required = {"record_source_nm", "source_reference_cd"}
    if not required <= set(frame.columns):
        print(f"{map_table}: skipped (CSV has no source-map columns)")
        return 0
    if "source_reference_nm" not in frame:
        frame["source_reference_nm"] = None

    # Replacement scope comes from every code set in the CSV, not only rows
    # that happen to contain a mapping. This also removes old mappings when a
    # rerun intentionally leaves all source-map values blank for a code set.
    code_sets = frame["code_set_nm"].dropna().unique().tolist()
    map_rows = frame[
        frame["record_source_nm"].notna() & frame["source_reference_cd"].notna()
    ].copy()

    if not map_rows.empty:
        # Adding mapping hash columns
        map_rows.insert(
            0,
            "mapping_record_hk",
            [
                hash_value(
                    row["record_source_nm"],
                    row["source_reference_cd"],
                    row["code_set_nm"],
                )
                for row in map_rows.to_dict("records")
            ],
        )
        map_rows.insert(
            1,
            "record_values_hash",
            [
                hash_value(row["source_reference_nm"], row[primary_code_col])
                for row in map_rows.to_dict("records")
            ],
        )
        map_rows["standard_lookup_hk"] = map_rows["lookup_hk"]
        map_rows["record_end_dttm"] = None
        map_rows["deleted_flg"] = False
        map_rows["active_flg"] = True
        map_rows["mapping_notes"] = "dev load from csv testing data"

    columns = [
        "mapping_record_hk",
        "record_values_hash",
        *METADATA_COLS,
        "record_end_dttm",
        "deleted_flg",
        "active_flg",
        "code_set_nm",
        "record_source_nm",
        "source_reference_cd",
        "source_reference_nm",
        "standard_lookup_hk",
        "mapping_notes",
    ]

    # Loading table <-- replace only this CSV's code sets. A full TRUNCATE
    # would delete mapping rows belonging to geography/office/situs_type
    # loaded by previous calls.
    target = table_identifier(map_table)
    with conn.cursor() as cur:
        cur.execute(
            sql.SQL("DELETE FROM {} WHERE code_set_nm = ANY(%s)").format(target),
            (code_sets,),
        )
        if not map_rows.empty:
            statement = sql.SQL("COPY {} ({}) FROM STDIN").format(
                target,
                sql.SQL(", ").join(column_identifier(column) for column in columns),
            )
            with cur.copy(statement) as copy:
                for row in map_rows[columns].itertuples(index=False, name=None):
                    copy.write_row(row)
    print(f"{map_table}: replaced with {len(map_rows)} row(s)")
    return len(map_rows)


@click.command()
@click.argument("csv", type=click.Path())
@click.option(
    "--trgt-table",
    required=True,
    help="target current-state table, including schema name",
)
@click.option(
    "--primary-code-col",
    required=True,
    help="column holding the primary code / business key",
)
@click.option(
    "--hist-table",
    default=None,
    help="historic table to replace from the same CSV (optional)",
)
@click.option(
    "--load-map/--no-load-map",
    default=True,
    help="also load source_reference_map rows when source columns are present",
)
@click.option(
    "--metadata-provided",
    is_flag=True,
    help="use metadata columns from the CSV instead of defaults",
)
@click.option(
    "--dsn",
    envvar="DATABASE_URL",
    help="Postgres connection string (default: DATABASE_URL)",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="run everything but roll back at the end",
)
def main(
    csv,
    trgt_table,
    primary_code_col,
    hist_table,
    load_map,
    metadata_provided,
    dsn,
    dry_run,
):
    """Load CSV testing data into the reference model."""
    if not dsn:
        raise ValueError("No connection string: set DATABASE_URL or pass --dsn")

    # The three loads share one timestamp when metadata is not supplied.
    effective = datetime.now(timezone.utc)
    with psycopg.connect(dsn) as conn:
        load_current_lkp_table(
            csv,
            trgt_table,
            primary_code_col,
            hist_table=hist_table,
            metadata_provided=metadata_provided,
            record_effective_dttm=effective,
            conn=conn,
        )
        if load_map:
            load_reference_map(
                csv,
                primary_code_col,
                metadata_provided=metadata_provided,
                record_effective_dttm=effective,
                conn=conn,
            )

        if dry_run:
            conn.rollback()
            print("[dry-run] rolled back — nothing was saved")
        else:
            conn.commit()


if __name__ == "__main__":
    main()